# import sys
import logging
from pygls.server import LanguageServer
from lsprotocol.types import (
    TEXT_DOCUMENT_COMPLETION,
    CompletionItem,
    CompletionItemKind,
    CompletionList,
    CompletionParams,
)

# Set up logging to output to a file, so it doesn't interfere with stdio JSON-RPC
logging.basicConfig(filename="axon_lsp.log", level=logging.DEBUG, filemode="w")
logger = logging.getLogger("axon-lsp")

# Initialize the Language Server
server = LanguageServer("axon-lsp-server", "v0.1.0")

@server.feature(TEXT_DOCUMENT_COMPLETION)
def completions(params: CompletionParams) -> CompletionList:
    """Provide basic Axon autocompletions."""
    logger.debug("Received completion request.")
    
    # In the future, this list will be dynamically generated by querying 
    # the remote SkySpark/Haystack database or parsing local .trio files.
    core_axon_functions = [
        CompletionItem(label="read", kind=CompletionItemKind.Function, detail="read(filter)"),
        CompletionItem(label="readAll", kind=CompletionItemKind.Function, detail="readAll(filter)"),
        CompletionItem(label="hisRead", kind=CompletionItemKind.Function, detail="hisRead(id, range)"),
        CompletionItem(label="filter", kind=CompletionItemKind.Function, detail="filter(grid, expr)"),
        CompletionItem(label="map", kind=CompletionItemKind.Function, detail="map(grid, expr)"),
        CompletionItem(label="now", kind=CompletionItemKind.Function, detail="now()"),
    ]
    
    return CompletionList(
        is_incomplete=False,
        items=core_axon_functions
    )

if __name__ == "__main__":
    logger.info("Starting Axon Language Server...")
    # start_io() initiates the JSON-RPC listener over standard input/output
    server.start_io()